### ISSUE TITLE
Current humidity unavailable on alecoair D12 home

### ISSUE THREAD

**Issue by romicaiarca** [make-all/tuya-local#1143]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

Current humidity is not available

**To Reproduce**
After update at last version of tuya local, it looks like the current humidity is not anymore available. I receive unvailable value for it in UI

**Expected behavior**
The current humidity to be a number

**Additional context**
I have made some changes into [alecoair_d12_home_dehumidifier.yaml](https://github.com/make-all/tuya-local/commit/da8e86691e897ec126404ca3c721b877402e6992#diff-b9b7b7b4962b130bcce340818ce3c3de08c8e75918c0396ddf3bbbfac2e7519a), and it looks like that changes from here (the commit in the url) makes the current humidity to be unavailable. After I've rolled back the changes, averything looks like works fine as before. Can you please check why you've changed those lines and if it is ok to rollback them?

**Comment by make-all** [comment]
This was a deliberate change, the sensor is deprecated, as Home Assistant added current humidity into the humidifier entity to use instead of separate sensors.

Although deprecated, the sensor is still available, that change should only add a warning into the log to prompt you to start using the alternative before the sensor is eventually removed.

Since you did not include any logs, it is impossible to say why your current humidity is showing as unavailable.

**Comment by make-all** [comment]
Looking at the code, there is some obsolete code still there that makes deprecated entities not enabled by default, but the config to enable them is no longer there.   This will need to be fixed.

**Comment by romicaiarca** [comment]
How can I test this? I've updated the component, removed the dehumidifier and add it back again and I cannot see the current humidity value.

**Comment by make-all** [comment]
If you remove the dehumidifier and add it back again, it is expected that the separate current humidity sensor will be disabled, since it is deprecated.  It will only be enabled by default if you update an existing installation which already had it enabled.  To enable a deprecated entity, you need to go into Settings / Devices and Services / Entities, Clear the filter which by default only shows enabled entities, find the entity and enable it.
