### ISSUE TITLE
Blitzwolf BW-SHP2 Smart Plug

### ISSUE THREAD

**Issue by Strixx76** [make-all/tuya-local#1262]
Just want you to know that this plug uses the exact same DPs as blitzwolf_bwshp6_smartplug.yaml and works perfectly. So maybe that should be rename to a more generic name?

**Comment by make-all** [comment]
It already has a generic name in the config, but some product ids (for both models) would be nice.

**Comment by Strixx76** [comment]
Well. I can create a pull request with the product id for SHP2 but I don't have any SHP6.

The question was if the filename should be more generic. Because it is the filename that is shown for the user in the config flow and not the name. But that is maybe something that you plan to change?

I was quickly reading the code and I can't see that there is any matching done for the product id, but maybe I missed it?

**Comment by make-all** [comment]
There currently isn't matching done on product id, as there is no way known to request it from the device after connecting.  But it is planned as part of automatic device discovery in future.
Config flow also needs to change to show the name rather than filename, and details of what entity states would be available from the config, to help with choosing from available configs (especially for Zigbee temperature/humidity sensors, where configs vary only by scale, and lots of generic devices are using the same layouts)
