### ISSUE TITLE
Moes IR hub wont discover

### ISSUE THREAD

**Issue by pacmac** [make-all/tuya-local#1294]
Not really sure if this is a bug, but the devices.md states that the MOES IR remote is supported:

`Air conditioner / heatpump via Moes IR hub`

I ran `python -m tinytuya wizard` and it correctly discovered the IR device:

```
        {
            "id": "bf63c82f-----4a502hrz0",
            "ip": "192.168.0.181",
            "active": 2,
            "encrypt": true,
            "productKey": "ke----3jwufkvh9r",
            "name": "",
            "key": "",
            "mac": "",
            "ability": 0,
            "token": "",
            "wf_cfg": "",
            "dev_type": "default",
            "origin": "broadcast",
            "ver": "3.3"
        },
```

However when I attempt to add the device using the integration I get the error:

`Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.`

I know for sure that the device ID, local key and IP address are correct, I have tried auto version as well as V3.3 numerous times but it always fails to discover the device.

I have other devices working, I just cant seem to add this one ?

**Comment by make-all** [comment]
I'm not sure that there is just one model of Moes IR hub, the one that is supported is a specialist hub for air conditioning/heatpump remote control, which presents a climate device with temperature and humidity readings, and tracking the current state (as sent by the device - it can get out of sync if you control the device directly), rather than a general button code send-only IR controller.  The latter do not present any state on the local tuya protocol, so cannot currently be recognised.

In case your device is the supported controller, check #522 for potential issues.
