### ISSUE TITLE
Request support for HRV KCvents VT501-W

### ISSUE THREAD

**Issue by bepluy** [make-all/tuya-local#1349]
# Log Message
<details>
<summary>DPS: {"1": true, "101": false, "102": true, "103": false, "104": false, "105": false, "106": false, "107": false, "108": 778, "109": 158, "111": false, "112": false, "113": true}</summary>
```
2023-11-27 14:59:23.180 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches sh07_sprinkler_controller with quality of 54%. DPS: {"updated_at": 1701086357.0082805, "1": true, "101": false, "102": true, "103": false, "104": false, "105": false, "106": false, "107": false, "108": 778, "109": 158, "111": false, "112": false, "113": true}
2023-11-27 14:59:23.181 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
2023-11-27 15:16:24.371 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 662, "full_poll": false}
2023-11-27 15:16:26.846 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch new pending updates: {"1": {"value": false, "updated_at": 1701087386.8463442, "sent": false}}
2023-11-27 15:16:26.851 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch sending dps update: {"1": false}
2023-11-27 15:16:26.976 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "full_poll": true}
2023-11-27 15:16:27.093 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "101": false, "102": true, "103": false, "104": false, "105": false, "106": false, "107": false, "108": 662, "109": 183, "111": false, "112": false, "113": true, "full_poll": false}
2023-11-27 15:16:27.208 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"113": false, "full_poll": false}
2023-11-27 15:16:27.324 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"102": false, "full_poll": false}
2023-11-27 15:16:27.554 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 650, "full_poll": false}
2023-11-27 15:16:29.585 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch new pending updates: {"1": {"value": true, "updated_at": 1701087389.5852993, "sent": false}}
2023-11-27 15:16:29.593 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch sending dps update: {"1": true}
2023-11-27 15:16:29.725 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": true, "full_poll": true}
2023-11-27 15:16:29.849 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": true, "101": false, "102": false, "103": false, "104": false, "105": false, "106": false, "107": false, "108": 650, "109": 183, "111": false, "112": false, "113": false, "full_poll": false}
2023-11-27 15:16:29.968 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"113": true, "full_poll": false}
2023-11-27 15:16:30.088 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"102": true, "full_poll": false}
2023-11-27 15:16:30.544 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 641, "full_poll": false}
2023-11-27 15:16:33.540 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 636, "full_poll": false}
2023-11-27 15:16:33.658 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"109": 184, "full_poll": false}
2023-11-27 15:16:36.633 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 628, "full_poll": false}
2023-11-27 15:16:36.754 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"109": 183, "full_poll": false}
2023-11-27 15:16:39.722 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 614, "full_poll": false}
2023-11-27 15:16:42.792 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 598, "full_poll": false}
2023-11-27 15:16:45.790 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 584, "full_poll": false}
2023-11-27 15:16:48.872 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 574, "full_poll": false}
2023-11-27 15:16:51.957 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"108": 567, "full_poll": false}
```
</details>

```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1701038599041,
        "value": true
      },
      {
        "code": "speed_one",
        "custom_name": "",
        "dp_id": 101,
        "time": 1701034713524,
        "value": false
      },
      {
        "code": "speed_two",
        "custom_name": "",
        "dp_id": 102,
        "time": 1701038599281,
        "value": true
      },
      {
        "code": "speed_three",
        "custom_name": "",
        "dp_id": 103,
        "time": 1701033408235,
        "value": false
      },
      {
        "code": "sleep_mode",
        "custom_name": "",
        "dp_id": 104,
        "time": 1701033366512,
        "value": false
      },
      {
        "code": "huimidity_one",
        "custom_name": "",
        "dp_id": 105,
        "time": 1701033367380,
        "value": false
      },
      {
        "code": "huimidity_two",
        "custom_name": "",
        "dp_id": 106,
        "time": 1701033368610,
        "value": false
      },
      {
        "code": "huimidity_three",
        "custom_name": "",
        "dp_id": 107,
        "time": 1700814338139,
        "value": false
      },
      {
        "code": "huimi",
        "custom_name": "",
        "dp_id": 108,
        "time": 1701038674130,
        "value": 327
      },
      {
        "code": "temper",
        "custom_name": "",
        "dp_id": 109,
        "time": 1701038674148,
        "value": 216
      },
      {
        "code": "in_mode",
        "custom_name": "",
        "dp_id": 111,
        "time": 1701033369321,
        "value": false
      },
      {
        "code": "out_mode",
        "custom_name": "",
        "dp_id": 112,
        "time": 1700938380962,
        "value": false
      },
      {
        "code": "auto_mode",
        "custom_name": "",
        "dp_id": 113,
        "time": 1701038599198,
        "value": true
      }
    ]
  },
  "success": true,
  "t": 1701038674379,
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"00000338x2\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"ON/OFF\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"speed_one\",\"description\":\"\",\"name\":\"Low Speed\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"speed_two\",\"description\":\"\",\"name\":\"Medium Speed\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"speed_three\",\"description\":\"\",\"name\":\"High Speed\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"sleep_mode\",\"description\":\"\",\"name\":\"Sleep mode\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"huimidity_one\",\"description\":\"\",\"name\":\"Low Humidity\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"huimidity_two\",\"description\":\"\",\"name\":\"Medium Humidity\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"huimidity_three\",\"description\":\"\",\"name\":\"High Humidity\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"huimi\",\"description\":\"\",\"name\":\"humidity\",\"typeSpec\":{\"max\":10000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"temper\",\"description\":\"\",\"name\":\"temperature\",\"typeSpec\":{\"max\":10000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"in_mode\",\"description\":\"\",\"name\":\"Fresh Air Mode\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"out_mode\",\"description\":\"\",\"name\":\"Exhausted Air Mode\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":113,\"accessMode\":\"rw\",\"code\":\"auto_mode\",\"description\":\"\",\"name\":\"Regenerate Mode\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1701087659661,
  "tid": "6c4176628d1f11eeb675fa6037e836b7"
```

# Product ID

```
{
  "result": [
    {
      "active_time": 1687353365,
      "category": "xfj",
      "create_time": 1687353365,
      "custom_name": "HRV",
      "icon": "smart/icon/bay16159719729188XMP/0695dc84d3c32b9a87acfd08d54ea028.png",
      "id": "bfaad9eb32d9507f89avzo",
      "ip": "xxxxxxxxxx",
      "is_online": true,
      "lat": "xxxx",
      "local_key": "",
      "lon": "xxxx",
      "model": "",
      "name": "Heat Recovery Ventilator",
      "product_id": "5p0togo3y3yzgp2p",
      "product_name": "Heat Recovery Ventilator",
      "sub": false,
      "time_zone": "+03:00",
      "update_time": 1701033539,
      "uuid": "065212efd4579d2e"
    }
  ],
  "success": true,
  "t": 1701087730267,
  "tid": "966afcf68d1f11ee98a1b60f6f2e1cb1"
}
```

**Comment by make-all** [comment]
The way this device splits its settings across multiple dps makes it difficult to support, unless that rather dipswitch like control interface is just simply copied instead of trying to integrate it as native Home Assistant entities..

**Comment by bepluy** [comment]
Dps 108 and 109 are just temp. and hum. sensors. Others are like dipswitches - on/off. Global switch - id 1, others are speed, vent. modes. And probably if you set "code": "speed_three" - to true, then other speeds become false. 
So i think it's ok to integrate this device just with switches - and use it in scenes or automations.
Or we need to make it suitable for fan or climate integration ?

**Comment by perimos** [comment]
I would also welcome the support of the HRV KCvents and have tried my hand at a device configuration. Due to this special distribution to individual dipswitches, I was unable to work out a nice solution.

@make-all: are you planning to support this special behavior at some point or have I overlooked how to do it? It would need something like that:

| ID 104 | ID 101 | ID 102 | ID 103 | speed percentage | 
|:-------|:-------|:-------|:-------|:-----------------|
| 1      | x      | x      | x      | 0%               |
| 0      | 1      | 0      | 0      | 33%              |
| 0      | 0      | 1      | 0      | 67%              |
| 0      | 0      | 0      | 1      | 100%             |


Without this functionality, the device would look like this (ugly, but works in general):

![Screenshot 2024-10-26 172951](https://github.com/user-attachments/assets/994a8660-8731-48b4-8761-20c2a4765bba)

**Comment by make-all** [comment]
No, I don't have any plan to cater to this type of multi-boolean instead of integer encoding in the short-medium term.
If you want to add an ugly config based on what is possible, then I will include it.

**Comment by perimos** [comment]
Thank you for your feedback. I will test a little more and open a pull request in the next few days.

**Comment by make-all** [comment]
I might suggest instead of Speed 0,1,2,3, you could use Speed 1, 2, 4, 8 which gives some hint that you can add them to create speeds up to 15.

**Comment by perimos** [comment]
No, unfortunately it is not the case that the fan offers 15 levels. It only has 3 levels (33%, 67%, 100%) and the sleep mode (0%). However, I have seen in the meantime that the device overwrites the other modes in sleep mode and sets the bit at 33% for speed.
I therefore suggest adding sleep mode to the other modes:

![Screenshot 2024-10-27 091036](https://github.com/user-attachments/assets/b2d5870f-681c-4993-97fb-c349822de2a4)

**Comment by make-all** [comment]
In that case you might be able to use value_redirect to chain the values. I thought they had to be all added, which would make it impossible with the current capabilities of the integration.

Something like:
```
  - id: 101
    type: boolean
    name: speed
    mapping:
      - dps_val: true
        value: 33
      - dps_val: false
        value_redirect: speed2
  - id: 102
    type: boolean
    name: speed2
    mapping:
      - dps_val: true
        value: 66
      - dps_val: false
        value_redirect: speed3
  - id: 103
    type: boolean
    name: speed3
    mapping:
      - dps_val: true
        value: 100
      - dps_val: false
        value: 0
```

I'm not 100% sure this will work, as I haven't chained value_redirects in any previous config, but if it does it might allow a better interface (a fan entity rather than a group of switches)

**Comment by perimos** [comment]
Thanks for the suggestion. It correctly shows the speed in HomeAssistant when I set it in the app. However, it is not possible to control the speed from HomeAssistant.

Do you see any other solution with more options? Or would the options 66% and 100% already have to be “announced” in ID 101?

Unfortunately, it's my only fan in my system, so I don't have a working example to make comparisons. But perhaps interesting: in the developer tools it shows the attribute “percentage_step: 100”. Shouldn't that be set to 33% for the 3 possible states?

**Comment by make-all** [comment]
Maybe they need to be announced in the speed dp, as you say. I don't know if it will be possible to do this, as using dummy values will lead to incorrect behaviour. The current code only really deals with two linked dps, any more just makes things exponentially more complex so I didn't implement it.

**Comment by perimos** [comment]
I'll play around a bit and get back to you as soon as I have time. But thank you very much so far.

**Comment by perimos** [comment]
The following seems to work:

```
    - id: 101
      type: boolean
      name: speed
      default: false
      mapping:
        - dps_val: true
          value: 33
        - dps_val: dummy_speed1
          value: 66
          value_redirect: speed2
        - dps_val: dummy_speed2
          value: 100
          value_redirect: speed3
        - dps_val: false
          value_redirect: speed2
    - id: 102
      type: boolean
      name: speed2
      default: false
      mapping:
        - dps_val: true
          value: 66
        - dps_val: false
          value_redirect: speed3
      hidden: true
    - id: 103
      type: boolean
      name: speed3
      default: false
      mapping:
        - dps_val: true
          value: 100
        - dps_val: false
          value: 0
      hidden: true
```

Is there anything against it? If not, I would do the same for the modes during the next week.

**Comment by make-all** [comment]
If it works and does not result in the dummy values being sent to the device when setting any of the options (which might cause problems), then it should be OK.

**Comment by Karolko0** [comment]
Description

Hello, I’m having an issue with the KC Vents VT-501 unit when using Tuya Local (version 2026.3.0) in Home Assistant.

I’m unable to properly control the fan speed (low / medium / high), and I also cannot switch between modes. The options appear correctly in the UI, but whenever I select a speed or mode, the fan always switches to maximum speed.

Configuration

I’m using the following configuration file:
kcvents_vt501_fan.yaml from make-all.

Expected behavior

Fan speed should change according to the selected option (low / medium / high).

Mode switching should work as selected in the UI.

Actual behavior

Any speed or mode selection results in the fan running at maximum speed.

Environment

Home Assistant version: (add your version)

Tuya Local version: 2026.3.0

Device: KC Vents VT-501

Config: kcvents_vt501_fan.yaml (make-all)

Question

Has anyone experienced this issue or knows if the configuration needs to be adjusted for the VT-501?

**Comment by perimos** [comment]
Hi @Karolko0,

I haven't used the fan for a few weeks, so I didn't notice the issue myself. But I can confirm that it's not working for me either (though I'm not sure which version it started with). I'll look into it in a week - but maybe you could take a quick look yourself in the meantime?

**Comment by Karolko0** [comment]
hi @perimos   AI Claude solved it...
Problem:

The KCvents VT-501 device does not use a standard integer value for fan speed. Instead, it uses three separate boolean datapoints (DP101, DP102, DP103), where only one can be true at a time.

Speed mapping:

33% → DP101=true, DP102=false, DP103=false
66% → DP101=false, DP102=true, DP103=false
100% → DP101=false, DP102=false, DP103=true

Why previous attempts did not work:

fan.set_percentage — tuya-local 2026.3.x has a bug and always results in 100% speed

fan.set_preset_mode with low/medium/high — these preset_mode values do not exist for this device

localtuya.set_dp — this service does not exist because the integration used is tuya_local

tuya_local.set_dp — the service does not exist in this version

select.select_option — same behavior as fan.set_percentage; the value_redirect chain does not work for write operations in tuya-local 2026.3.x

Solution:

The working approach was to define three separate switch entities in YAML, one for each datapoint (DP101, DP102, DP103).

Example:

switch for Speed Low → DP101

switch for Speed Medium → DP102

switch for Speed High → DP103

From the dashboard, only a single switch.turn_on command is sent to the selected speed switch.

The device automatically turns off the other two datapoints. This appears to be the device’s native behavior, which was confirmed through debug logs.
``

<img width="498" height="838" alt="Image" src="https://github.com/user-attachments/assets/975cf2a6-8671-4a9d-b080-2f0aba410787" />

[kcvents_vt501_fan.yaml](https://github.com/user-attachments/files/25999550/kcvents_vt501_fan.yaml)

**Comment by make-all** [comment]
I am really not interested in AI's hallucinations about the cause and its eventual solution to revert to a raw dipswitch interface instead of a natural fan speed. It would be better to capture debug logs of the speed being changed in the UI so the problem can be studied by someone with actual understanding and not just an advanced google result statistical analysis reasoning model.

**Comment by Karolko0** [comment]
Hi @make-all    The AI may be hallucinating, but it provided a working solution for my case. Ultimately, the result is what matters. I’ve outlined the steps I took to serve as a guide for others.

**Comment by make-all** [comment]
It is likely broken by this change last November:
https://github.com/make-all/tuya-local/commit/5845ac5386cf957ab24acbae43c2fa9b0b2a6f52

The code now evaluates the value_redirects first, based on the current state, before applying changes. This was needed for some other complex logic, but it seems this device needs to adapt to the new method (which may mean repeating the conditions in each switch dp to allow the code to figure out where to go next, or it may just need a different default condition in the terminal case to allow exiting that state into the others).

I'd suggest making a separate bug report with debug logs, so the test data is available for whoever attempts a fix to run through the scenario and verify the fix.

**Comment by perimos** [comment]
Hi @make-all,
I suspected something like this and appreciate you pointing out the change in November right away.
I won’t have time to look into it for about a week, but I’d be happy to help create or review the fix if someone else manages to get to it before I do.

I also prefer to fix it properly rather than work around it with individual switches.
