### ISSUE TITLE
BHT-6000 after HA restart set desired temperature random to low value

### ISSUE THREAD

**Issue by antoweb** [make-all/tuya-local#156]
As the title sometimes after HA restart the target temperature goes to low value like: 5 or 9

**Comment by make-all** [comment]
Do you have any automations that might be responsible? The component itself only sends commands when told. For a long time I thought my heatersand lights  turning on when HA started was something caused by the integration, until automation debugging was introduced and I saw that at startup the weather and people counter were cleared to 0 so the automation triggered as people arriving home in 0 degree weather. I ended up adding a condition so those automations would not trigger within 2 minutes of startup.

**Comment by antoweb** [comment]
Yes, I have two automations that turn off the thermostat if no one is at home but I have just tried and when the family returns to the home state the thermostat has not changed the temperature

**Comment by make-all** [comment]
There have been a lot of changes since this unexplained behaviour was reported.  I wonder if the problem is still occuring.

**Comment by antoweb** [comment]
Not more happened from time. I think isnpossible to close this issue

**Comment by make-all** [comment]
Thanks
