### ISSUE TITLE
Error for devices with local keys containing special characters 

### ISSUE THREAD

**Issue by i8nemo** [make-all/tuya-local#1572]
Since tuya dev began using special characters in the device local keys, I have not been able to register these devices in tuya local

Eg of local key for device that was working before

n:Gkz]^d]U_6F~of

**Comment by make-all** [comment]
There is no issue with "special characters".  This keeps being reported repeatedly, and every time users find some other issue in their config, like using the uuid instead of the device id, not entering the IP address, or the device is unable to auto detect protocol version so it has to be explicitly set.
