### ISSUE TITLE
Support for Door Sensors

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#160]
Currently the local tuya integration while allowing these to be set up doesn't detect them well, they drop out and lose connection all the time and ultimately end up sitting in a constant unavailable state. As such I'd love to see if you're able to get them supported

Are you looking at supporting the door/window sensors in the future and if so, if you need me to get any information for you from my door sensor I'd be happy to pass it on.

**Comment by make-all** [comment]
They will have the same problem as localtuya, since this integration also only does local polling to communicate with devices, and like you said, they drop off the network and go into hibernate mode most of the time, waking only to report to the cloud.

I think you'd have more luck with the standard tuya integration that uses the cloud.

**Comment by Krispkiwi** [comment]
No worries, thanks for getting back to me.
