### ISSUE TITLE
Moes BHT-002GCL WIFI - Home assistant problems

### ISSUE THREAD

**Issue by mojrs10** [make-all/tuya-local#171]
Sometimes the connection to the thermostat is lost, and I noticed that the temperature or mode of operation of the thermostat in the Home assistant is not updated.

**Comment by make-all** [comment]
There can be a number of reasons for connection issues:

1. As most Tuya based devices use a prebuilt module with PCB printed antenna, their range is not the best and they may be more sensitive to interference than your other Wifi devices.
2. The Tuya modules only allow one local connection at a time.  This implementation polls in order to not lock out other things from accessing the device, but if you open the app on your phone, it may make a persistent connection, blocking other connections.
3. If the commands being sent to the device are not quite right, a lot of devices seem to have poor error handling, and may be crashing and going off line for a few minutes until they watchdog reboot.
