### ISSUE TITLE
adding gateway or devices connected to gateway not possible

### ISSUE THREAD

**Issue by Lonelysoulman** [make-all/tuya-local#1786]
Hello,

i cant add my gateway or any device connected to the gateway to the integration. it always says: 
Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.

but the entered id and keys are correct.

hope someone can help here

**Comment by make-all** [comment]
A bug report requires evidence that shows a problem happening in the integration.  What you are describing is difficulty finding the right settings for your device. That is covered in discussion #522

**Comment by sk2andy** [comment]
@Lonelysoulman
1) list all devices somewhere: gateway device id and sub device id.
2) go to the cloud api explorer and search for "Query Device Details in Bulk"
3) type in the device ids and run the request - it will return a json per device with a field `uuid` in it. Use that one instead of the device ids
