### ISSUE TITLE
It's broken!

### ISSUE THREAD

**Issue by meluvalli** [make-all/tuya-local#2040]
"Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

I think it's not a intermittent issue.  It's a permanent issue.

I entered my information EXACTLY the same as tinytuya python script which works!

**Comment by make-all** [comment]
This tracker is for bug reports, not complaints without detail

**Comment by Azarath7** [comment]
@make-all, first of all, thank you for your hard work! I had been avoiding using local Tuya due to the difficulty of obtaining all the required keys. Yesterday, I discovered your project and was very happy until I encountered "Unable to connect" error. I'm new to homeassistant and smart home stuff, so if you need logs - tell me, I will send them as soon as I figure out how.

I am using a Tuya Zigbee hub to control my devices. With this integration, I was able to add two devices without any problems. However, I soon ran into this error. My Zigbee hub's IP address is 192.168.88.206, and both devices that I have successfully added, used this IP address. For the remaining devices that were also controlled by Zigbee Hub, they also used this same IP, but I was unable to add them. Maybe there is a limit of how many devices you can control using one IP address? I managed to add another device through this integration, though that device was using a different IP address.

**Comment by Azarath7** [comment]
So far I have tried using all available protocol versions, rebooting my Raspberry Pi, reconnecting Zigbee devices, but no luck…
