### ISSUE TITLE
Can't find Tuya local in integrations

### ISSUE THREAD

**Issue by Agenciate** [make-all/tuya-local#21]
I added the custom repository in hack, installed it and reinitialized HA. When I go to add new integration, I don't get it in the list of integrations. In Hack it shows the integration Tuya local devices and if I go into the custom components folder, it is there. How can I fix it?

**Comment by make-all** [comment]
It shows up labelled as "Tuya based devices local control" with the same Tuya icon as the built in cloud Tuya integration.

If it isn't showing up for you, check your Home Assistant log to see if there were download errors.  Yesterday there was a major outage affecting a large part of the internet, including reportedly github, so your installation may have failed due to that.

**Comment by Agenciate** [comment]
I have looked in the log, but there is nothing related to local Tuya. I uninstalled the integration and restarted. I installed the original version of Local Tuya and it does find it. Once I installed the original version and restarted the HA, the same thing happens as with your version. It does not find it in the integrations, the folder in HACKS exists and in the log there is nothing related. I don't know what it could be.

**Comment by make-all** [comment]
Sorry, I'm a bit confused here. What version are you referring to as the the original version, and do you mean the same version that worked before does not show up now?

**Comment by Agenciate** [comment]
I'm sorry I didn't explain it well.  I can only install this version of Local Tuya: https://github.com/rigibe/localtuya. 

After installing yours and it did not appear in integrations, even this one I have not been able to reinstall. 

I had to uninstall Local Tuya, restore the backup with core version 6.2. And after upgrading again to 6.3 I can reinstall Local Tuya from rigibe repository. I tried the same process to install from make-all/tuya-local, but it doesn't work.

**Comment by make-all** [comment]
Re-reading your original comment, I think you have not added a device yet.  On the list of integrations, this will not show up until you press the (+) button at bottom right, then you can type "Tuya", and you should see this integration show as "Tuya based devices local control"  along with the default "Tuya" cloud integration, this will start the config flow for adding a device.

**Comment by make-all** [comment]
I think with the change to avoid confusion over naming, there is nothing further I can do on this.
There is no problem identified with the actual integration here, and there seems to be either a general problem with the Home Assistant installation, as the problem also occurs on other integrations, or the problem is down to user confusion which is addressed with the naming commit and the comment above about adding devices.
