### ISSUE TITLE
Hydrotherm X8 no longer accepting turn on and turn off commands

### ISSUE THREAD

**Issue by Brazen00** [make-all/tuya-local#2315]
**Describe the bug**
Since updating to HA 2024.9.2 from 2024.8.3, my Hydrotherm X8 has been unable to accept turn_off and turn_on commands.

**To Reproduce**
I have these as part of automations. However, going to "developer tools">actions and choosing water_heater.turn_off results in ```Failed to perform the action water_heater.turn_off. Entity water_heater.hot_water_system does not support this service.```

**Expected behavior**
Previously was able to turn the water heater on and off.

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[tuya_local-767d2942d03cfec902939d15bfa05c7d-Hot Water System-10d0d5440ccf8be9ba51c5a846e16e4c.json](https://github.com/user-attachments/files/17040914/tuya_local-767d2942d03cfec902939d15bfa05c7d-Hot.Water.System-10d0d5440ccf8be9ba51c5a846e16e4c.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Please report to Home Assistant, not here, as the unadvertised change was made on their side:

https://github.com/home-assistant/core/commit/99ab2566c25a3ba40b205302065740907675bd84

**Comment by make-all** [comment]
On looking further, since the comments on the PR seem to suggest they were removing a duplicate service registration with that change, it seems that there was always an ON_OFF feature flag to go with the on/off service, but probably the explicit duplicate made it work without declaring that, so it wasn't detected that the feature flag was missed when adding on/off support to this integration following the same pattern as for climate (which at the time did not have such a flag).

So maybe it can be fixed in this integration.

**Comment by Brazen00** [comment]
Thanks for following up
