### ISSUE TITLE
switch auto turn off after few second 

### ISSUE THREAD

**Issue by peceq** [make-all/tuya-local#273]
Hi my tuya switches with RF turn off automatically after few seconds (about 30s) of being turned on. when i disable entities from tuya-local integration, these switches come back to proper work.

**Comment by make-all** [comment]
In 2022.12.1, there is the possibility to set the protocol version explicitly.  If this is being caused by the auto-detected protocol not being a perfect match for the device, then it may help to choose an explicit protocol.  It may take some experimenting to find the correct protocol, but the most likely mismatch is 3.2 being misdetected as 3.3 I think.
