### ISSUE TITLE
Bug: cant add smart plug power entity to energy dashboard (working on fix)

### ISSUE THREAD

**Issue by Kulturnilpferd** [make-all/tuya-local#287]
Hey there, 
as the title claims I can't add an entity to the energy dashboard. There is a link provided in the dropdown if it can't find entities (Link: https://www.home-assistant.io/more-info/statistics/). Is this really a bug or do I have something missed or configured badly?

**Comment by Kulturnilpferd** [comment]
Ah have found what cause it, we need to add a sensor to the smartplugv2.yaml so that it can have this entity to monitor it:
https://www.home-assistant.io/integrations/integration/#energy

**Comment by Kulturnilpferd** [comment]
Hm, added 
`sensor:
  - platform: integration
    source: sensor.current
    name: energy_spent
    unit_prefix: k
    round: 2`
to the bottom line of smartplugv2.yaml but can't find it in the entity list of the energy dashboard configuration... Did I miss something?

**Comment by make-all** [comment]
You need to add that to your Home Assistant configuration.yaml.  And you should use the power rather than current to get a proper Wh reading.  The "integration" integration is a separate integration from this one, so cannot be configured from the internal configuration files for this ntegration.

Some Tuya devices do have an energy dp, but they seem to reset the counter whenever they report usage to the cloud, so you see them go to 1 briefly every 0.1kWh (or whatever scale they are using), then back to 0.  As this may be missed by the local polling, even using a total_increasing sensor for this will not be useful, so an integration sensor on the power sensor
