### ISSUE TITLE
Turn on action overrides program mode for climate

### ISSUE THREAD

**Issue by nerodoxus** [make-all/tuya-local#302]
Turn On action on the climate entity always sets the Manual Mode on the thermostat, no matter which mode was set before. It's also set the last temperature.
I think it's maybe related to retain option set somewhere?
I see on my tuya iot portal:

2022-12-05 15:51:19 | Report | Set Temperature | 21.50℃ | device itself   
2022-12-05 15:51:19 | Report | Mode | Manual mode | device itself   
2022-12-05 15:51:19 | Report | Switch | ON | device itself

Desired behaviour would be to restore last state of the thermostate including working mode.

**Comment by make-all** [comment]
Currently the tuya-local climate implementation inherits the default  turn_on, turn_off and toggle behaviour from the Home Assistant climate platform.  But since most Tuya devices use a boolean on/off switch and a separate mode dp if they support more than one mode, maybe this can be overridden to only toggle the switch for these calls.  But this will need some exceptional handling of the dps mappings on the Tuya side as well as overriding these functions (if that is possible) on the Home Assistant side, since the current handling is based around making Tuya devices work the way Home Assistant expects, not vice-versa.

**Comment by make-all** [comment]
The latest version supports independant turn_on/off commands without affecting hvac_mode for devices that have this undrerlying functionality (which is almost all).
