### ISSUE TITLE
expose HVAC current_tempature as a sensor

### ISSUE THREAD

**Issue by ohadlevy** [make-all/tuya-local#327]
Hello,

Would it be possible to expose the current temperature field as a sensors in HA? - for example, this is the climate entry the integeration generate for my device:
```
hvac_modes:
  - fan_only
  - heat
  - 'off'
  - cool
min_temp: 5
max_temp: 35
target_temp_step: 0.5
fan_modes:
  - low
  - auto
  - medium
  - high
preset_modes:
  - comfort
  - eco
current_temperature: 22
temperature: 20
fan_mode: auto
preset_mode: comfort
icon: mdi:home-thermometer
friendly_name: Name
supported_features: 25
```

**Comment by make-all** [comment]
What is the use case?  I"m sure you can access the current_temperature attribute on the climate entity in most contexts you would want this.

**Comment by ohadlevy** [comment]
thanks for your reply, its pretty simple, history tracking and simple display (without templating/helpers) on a dashboard.

**Comment by make-all** [comment]
History tracking is already available on climate entities.  And displaying attributes in an entities card is not difficult.

I don't think duplicating information into multiple entities is a useful goal, as it will affect performance, and if added at the integration level, everyone using the integration takes the performance hit whether they wanted it or not. Whereas using a template entity if you really need the separate sensor entity rather than an attribute only affects those who need it.

**Comment by ohadlevy** [comment]
thanks for taking the time looking into it...
