### ISSUE TITLE
New Device request "Inventor EVA ION PRO WI-FI" Dehumidifier

### ISSUE THREAD

**Issue by sohail579** [make-all/tuya-local#331]
Hi Please can you add support for this device? at the moment it just shows up as a simple switch

**Device Page**

https://www.inventorappliances.com/dehumidifiers/eva-ion-pro-wi-fi-20l

**Link to the Manual**

https://www.inventorappliances.com/manuals?item=eva-ion-pro-wi-fi

Tuya IoT Cloud information:

**Standard Instruction Set:**

switch | Boolean | "{true,false}"
dehumidify_set_value | Integer | {   "unit": "%",   "min": 35,   "max": 85,   "scale": 0,   "step": 5 }
fan_speed_enum | Enum | {   "range": [     "low",     "middle",     "high"   ] }
mode | Enum | {   "range": [     "manual",     "continuous",     "smart",     "drying"   ] }
anion | Boolean | "{true,false}"
pump | Boolean | "{true,false}"
water_level | Integer | {   "unit": "",   "min": 1,   "max": 4,   "scale": 0,   "step": 1 }

**Standard Status Set:**

switch | Boolean | "{true,false}"
dehumidify_set_value | Integer | {   "unit": "%",   "min": 35,   "max": 85,   "scale": 0,   "step": 5 }
fan_speed_enum | Enum | {   "range": [     "low",     "middle",     "high"   ] }
mode | Enum | {   "range": [     "manual",     "continuous",     "smart",     "drying"   ] }
humidity_indoor | Integer | {   "unit": "%",   "min": 30,   "max": 90,   "scale": 0,   "step": 1 }
temp_indoor | Integer | {   "unit": "℃",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
anion | Boolean | "{true,false}"
fault | Bitmap | {   "label": [     "10",     "11",     "38",     "37",     "1"   ],   "maxlen": 5 }
tank_full_alert | Boolean | "{true,false}"
pump | Boolean | "{true,false}"
water_level | Integer | {   "unit": "",   "min": 1,   "max": 4,   "scale": 0,   "step": 1 }

**Device Specification Attribute:**

{
  "result": {
    "category": "cs",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "dehumidify_set_value",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":35,\"max\":85,\"scale\":0,\"step\":5}"
      },
      {
        "code": "fan_speed_enum",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "mode",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"manual\",\"continuous\",\"smart\",\"drying\"]}"
      },
      {
        "code": "anion",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump",
        "dp_id": 103,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "water_level",
        "dp_id": 104,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":4,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "dehumidify_set_value",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":35,\"max\":85,\"scale\":0,\"step\":5}"
      },
      {
        "code": "fan_speed_enum",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "mode",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"manual\",\"continuous\",\"smart\",\"drying\"]}"
      },
      {
        "code": "humidity_indoor",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":30,\"max\":90,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_indoor",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "anion",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 19,
        "type": "Bitmap",
        "values": "{\"label\":[\"10\",\"11\",\"38\",\"37\",\"1\"],\"maxlen\":5}"
      },
      {
        "code": "tank_full_alert",
        "dp_id": 101,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump",
        "dp_id": 103,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "water_level",
        "dp_id": 104,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":4,\"scale\":0,\"step\":1}"
      }
    ]

**This is a screenshot of the Tuya Smart App**

![3](https://user-images.githubusercontent.com/57506081/210158408-816587a3-fbfe-4f9f-b444-f682a307002c.jpg)

hope this is the required information

**Comment by make-all** [comment]
I'm not sure about the pump and water level settings.  There is no mention in the manual, but they appear to be configurable from the app screenshot, and from the protocol info that lists them under "instruction set" rather than just "status set" like humidity and temperature sensors.

As there is no mention in the manual of a pump, I assume it is the compressor pump.  In which case, an indication of whether it is operating or idle makes more sense than a configuration switch.  And water level I presume is some indication of how much water is in the tank - but maybe it is in fact a configuration option for how much in advance to raise the "water level alarm".

For now, I've left them as attributes on the humidifier entity, until you can confirm for sure whether they are really a setting, or just indicators.

**Comment by sohail579** [comment]
Thanks for taking a look.  I dont think they do anything even in the Tuya App.

however I have connected the device to the manufacturers app and there is no mention of the two settings so i assume they have them in there as a set for a compatible device??

here are the screenshots from the manufacturers app

![Screenshot_20230107_131906_Inventor Control](https://user-images.githubusercontent.com/57506081/211154396-822f85b2-1dc4-450e-94db-a9fa4e69ecbe.jpg)
![Screenshot_20230107_131848_Inventor Control](https://user-images.githubusercontent.com/57506081/211154403-fd41689b-5b36-46c2-b048-ccaa4d9b4cbd.jpg)
![Screenshot_20230107_131852_Inventor Control](https://user-images.githubusercontent.com/57506081/211154404-f738e79e-bcaa-4d62-923b-0c4b981f32b2.jpg)

do i need to test this now? if so how do i test the changes you have made?
![Screenshot_20230107_131857_Inventor Control](https://user-images.githubusercontent.com/57506081/211154405-6130c737-b585-4d9c-9983-9b2fc8f7893b.jpg)

**Comment by make-all** [comment]
If you want to test now, if you are using HACS, you can select "Redownload" from the menu inside the details page for this integration in HACS, then select "main" as the version to install.
If you installed manually, fetch the git HEAD rather than a release tag.

Otherwise I will leave this open until after I have made a release so you can get a chance to test it then.

**Comment by sohail579** [comment]
Thanks I tried this in HACS but its not working yet. It still shows up as simple switch.  Looking in the directory I don't see a configuration for the device either

**Comment by make-all** [comment]
Since the config directory was missing the file, you probably did not manage to install the main branch.  This is now released, so updating to the latest release should bring the config in.

**Comment by sohail579** [comment]
> Since the config directory was missing the file, you probably did not manage to install the main branch. This is now released, so updating to the latest release should bring the config in.

thanks I will give it a test and feedback

**Comment by make-all** [comment]
1. Thank you for confirming
2. This is expected, as the on/off switch is relevant to both the humidifier entity and the fan entity.  The fan does not show a switch by default when added to Lovelace, as turning the speed down to 0 also works to switch it off.
3. No, there is no device class for binary_sensor that has "OK" and "Full" as its default display output.
4. You can manually create buttons in your lovelace UI instead of using the default fan entity representation if you prefer.  Just set the button actions to call the fan.set_percentage with parameters of 33, 66 and 100 for Low, Mid, High respectively.
5. Again, you can manually create buttons in the lovelace UI for the modes, using humidifier.set_mode as the action.
6. Can you check in the Developer Tools / States screen, for the humidifier entity, what is listed in the Attributes column when the tank is full or removed?  Before making any alterations to the general Fault sensor, I want to confirm I have got the mapping of fault codes correct.

**Comment by sohail579** [comment]
> 1. Thank you for confirming
> 2. This is expected, as the on/off switch is relevant to both the humidifier entity and the fan entity.  The fan does not show a switch by default when added to Lovelace, as turning the speed down to 0 also works to switch it off.
> 3. No, there is no device class for binary_sensor that has "OK" and "Full" as its default display output.
> 4. You can manually create buttons in your lovelace UI instead of using the default fan entity representation if you prefer.  Just set the button actions to call the fan.set_percentage with parameters of 33, 66 and 100 for Low, Mid, High respectively.
> 5. Again, you can manually create buttons in the lovelace UI for the modes, using humidifier.set_mode as the action.
> 6. Can you check in the Developer Tools / States screen, for the humidifier entity, what is listed in the Attributes column when the tank is full or removed?  Before making any alterations to the general Fault sensor, I want to confirm I have got the mapping of fault codes correct.  I think I assumed that since there is a separate indicator dp for the tank, it would not show up under the general fault codes.

OK thanks for the info I will look into manually creating the Buttons.  

RE point 6.  where do i find this information?

**Comment by make-all** [comment]
Developer Tools on the left menu, States tab.  In the "Filter entities" search box at the top of the table, type your device name.  They should be listed in the right most column.

**Comment by sohail579** [comment]
Here it is

![image](https://user-images.githubusercontent.com/57506081/212893655-331aa98e-bbea-4ed7-aeb1-1abbf646c858.png)

**Comment by make-all** [comment]
Is the tank removed?  It is showing as no fault.

**Comment by make-all** [comment]
I guess the other fault condition that might be possible to catch, as it should happen in normal usage after a long period of being on, and you can probably hear the difference in the sound of the device (normally the fan will run at full speed while the compressor will stop), is the "Defrosting" one.  Currently I'm just guessing at the order based on the order they appear in the manual, but chances are that is wrong.

**Comment by sohail579** [comment]
I have had this on for a long while and never seen any other error codes.  the fan is mostly on if its running sounds like a fridge at times where something else turns on and off but never throws a code.  that being said i think its giving us all we need in that case.  I just need to figure out how to create the buttons from the slider and modes now

**Comment by make-all** [comment]
Prior to 2022.1.2, the updates were polled. The poll rate is controlled by Home Assistant, and apparently varies per platform, but was generally around 10 or 30s.

Since 2022.1.2, a connection is left open to the device all the time, so it is up to the device how quickly it sends info.  A lot of more complex devices have the Tuya module as an add-on to an existing microcontroller controlled device, so there may be some delay due to the way they are communicating between microcontrollers, but generally, the updates should be pretty quick.

**Comment by oliverbutler** [comment]
Hey @sohail579  I'm in the same boat with the Eva Ion Pro

How did you connect the device to Tuya cloud? The only app that has worked for me is InventorControl itself 

I've managed to locate the device on my network and have got its device id and Tuya version 3.3

I just need to jump through some hoops to get the local key 

Thanks!

**Comment by sohail579** [comment]
> Hey @sohail579  I'm in the same boat with the Eva Ion Pro
> 
> How did you connect the device to Tuya cloud? The only app that has worked for me is InventorControl itself 
> 
> I've managed to locate the device on my network and have got its device id and Tuya version 3.3
> 
> I just need to jump through some hoops to get the local key 
> 
> Thanks!

Hi @oliverbutler 

So there are 2 versions, one which uses  tuya and the other is midea air.  If it's the latter, there is an integration already available.  If it's the tuya you can add it to the tuya smart app manually, and you'll see it online it's how I got all the above info. The integration does need rework as a lot of the stuff has changed, but it still works, maybe if you can add it you get the info and get the integration updated.  Add it as a humidifier if I recall no option for a dehumidifier if I recall. Let  me know how you get on

**Comment by oliverbutler** [comment]
@sohail579 thanks for responding! 

its the Tuya version and I got it working, I'll post the steps here for anyone else who discovers this post ❤️

I couldn't connect it to the SmartLife app because when I went to pair "Dehumidifier (WiFi)" I clicked that it was "blinking quickly"

You **must** click "blinking slowly" to make it work - then it pairs perfectly like the Inventor Control app.

Once you connect to it, run "tinytuya" python CLI's wizard - it'll be the device id and local key.

That's it! You can use this integration in HA now with all the mapping working perfectly 

Another tip, my dehumidifiers humidity sensor isn't particularly accurate for real room humidity - make a "generic hygrostat" in HA using your accurate room/house humidity.

**Comment by sohail579** [comment]
> @sohail579 thanks for responding!
> 
> its the Tuya version and I got it working, I'll post the steps here for anyone else who discovers this post ❤️
> 
> I couldn't connect it to the SmartLife app because when I went to pair "Dehumidifier (WiFi)" I clicked that it was "blinking quickly"
> 
> You **must** click "blinking slowly" to make it work - then it pairs perfectly like the Inventor Control app.
> 
> Once you connect to it, run "tinytuya" python CLI's wizard - it'll be the device id and local key.
> 
> That's it! You can use this integration in HA now with all the mapping working perfectly
> 
> Another tip, my dehumidifiers humidity sensor isn't particularly accurate for real room humidity - make a "generic hygrostat" in HA using your accurate room/house humidity.

No Problem @oliverbutler glad you got it working and yes it works perfectly in HA ignore my previous comment I was doing something stupid :)  good call on the tinytuya learn somthing new every day

**Comment by GadgetUK** [comment]
Trying to install, device is found, but mappings appear to be broken.
