### ISSUE TITLE
Unsupported device - WiFi Digital Meter  -    PJ-1103 Power meter

### ISSUE THREAD

**Issue by MoosJ80** [make-all/tuya-local#336]
I have tried to add this device with different methods / integrations.
- Official Tuya integration
- LocalTuya
- Tuya-Local

The device is recognized but none of the entities..
Any help would be appreciated.
 
Model PJ-1103 (from official Tuya integration log)

https://nl.aliexpress.com/item/1005004845740618.html?spm=a2g0o.order_list.order_list_main.17.21ef79d26ELMmJ&gatewayAdapt=glo2nld

DP ID's
Cur Current	        	-	18
CUR Power		        -	19
Max Standby power	-	51
Cur Voltage		        -	20
Max Power		        -	52
Test Bit		                -	21
Voltage Coe		        -	22

![image](https://user-images.githubusercontent.com/101753441/210636363-8ea44785-2f32-432a-a636-768c04ab26e4.png)

**Comment by make-all** [comment]
Thanks, based on other users' reports for protocol version 3.4 devices, it may not be fully working yet.  But I have made some changes based on the additional info.

**Comment by Cook23** [comment]
Works nicely.

Thanks a lot

Pitty is it seems this device do not provide energy counter. Ok I will integrate power in HA.

**Comment by make-all** [comment]
I have never seen a Tuya device provide a usable energy counter.  The ones that do reset their counter as soon as they have reported the increment to the cloud, so it works more like a flashing light on your meter that you might miss than an energy reading.

**Comment by Cook23** [comment]
This one works perfectly well. It have an endless counting counter for energy. Endless at least since 6 month and 7500 kWh counted. https://community.home-assistant.io/t/tuya-1-or-3-phase-energy-meter/351386/10

I use "localtuya" for it. I don't know if you support it. Here are the info about it :

Tuya Protocol Version = 3.3

"category": "zndb",
"product_name": "Power Clamp",
"product_id": "r64livttuufctble",
"biz_type": 0,
"model": "PC321",
"sub": false,

DP List :

N° | Libellé | Phase | Scale | Unit

101 | Tension | 1 | 0.1 | V
102 | Courant | 1 | 0.001 | A
103 | Puissance | 1 | 1 | W
104 | Cos phi | 1 | 0.01 | 1
106 | Energie | 1 | 0.01 | kWh
 
111 | Tension | 2 | 0.1 | V
112 | Courant | 2 | 0.001 | A
113 | Puissance | 2 | 1 | W
114 | Cos phi | 2 | 0.01 | 1
116 | Energie | 2 | 0.01 | kWh

121 | Tension | 3 | 0.1 | V
122 | Courant | 3 | 0.001 | A
123 | Puissance | 3 | 1 | W
124 | Cos phi | 3 | 0.01 | 1
126 | Energie | 3 | 0.01 | kWh

131 | Energie | Total | 0.01 | kWh
132 | Courant | Total | 0.001 | A
133 | Puissance | Total | 1 | W
135 | Frequence | Total | 1 | Hz
136 | Temperature | Total | 0.1 | °C

**Comment by make-all** [comment]
Yes, there is that one, and another dedicated electricity meter that support energy properly.  I was thinking of the power sockets that have an "add_ele" dp that only ever reads 0 or 1 in normal usage (I suspect they may go higher if offline).

**Comment by MoosJ80** [comment]
It is working now.
Thanks a lot!

**Comment by MoosJ80** [comment]
> Works nicely.
> 
> Thanks a lot
> 
> Pitty is it seems this device do not provide energy counter. Ok I will integrate power in HA.

Have you got a short instruction how to do this?

**Comment by Cook23** [comment]
> Have you got a short instruction how to do this?

Only few clics needed from Settings / Integration-Devices-Entities-Helpers Click on "Helpers" or whatever it's renamed in your laguage. Then Add. Then choose Riemann Integrate. Then configure the box and choose "left Riemann".

https://www.home-assistant.io/integrations/integration/

**Comment by imgkaisser** [comment]
Hi, I have the same device (confirmed with the device id matching the id inside the update yaml of localtuya), but after the last update, this device keeps saying "Not supported"
The device is working perfectly with smart life, how have you configured it to work correctly?
Thanks in advance

**Comment by MoosJ80** [comment]
> Hi, I have the same device (confirmed with the device id matching the id inside the update yaml of localtuya), but after the last update, this device keeps saying "Not supported" The device is working perfectly with smart life, how have you configured it to work correctly? Thanks in advance

You should update the integration and probably restart HA

**Comment by MoosJ80** [comment]
Unfortunately the device becomes unavailable after a few hours.

**Comment by Cook23** [comment]
are you sure your device have a static IP?

**Comment by imgkaisser** [comment]
I have reinstalled the complete component, restarting afterwards and even turning it off and on.
I have the tuya-local version 2023.1.0, I have the device with a fixed ip by mac on the router and I have checked that it is well connected, in smart life it works out perfectly, without cuts, with a good signal and without any problem.
What I can be doing wrong? I keep getting device not supported

**Comment by make-all** [comment]
Please open a new issue if the problem is still there in 2023.1.1

**Comment by jesusmendez87** [comment]
Hi!
The id 18 does not add up in HA the same as in the application. I am trying to count with utility-meter but it does not add in a similar way to the application. Has anyone managed to count the accumulated consumption of kw/h?

**Comment by make-all** [comment]
Use an integration helper on the power sensor.  

The "add_ele" dp of Tuya devices is not as useful for kWh measurement as they first appear, since they reset to zero immediately after incrementing (probably immediately after reporting the increment to the cloud), so end up being more like counting led flashes on a non-smart meter than a useful kWh measurement.

**Comment by Casadomoticap** [comment]
It seems that still not supported? How do you integrate it? When I try the message "Sorry, there is no support for this device" appears :/ 

I use the 2023.2.0 version of it. Any help please?
