### ISSUE TITLE
LEXY F501 Fan support request

### ISSUE THREAD

**Issue by Johnnybyzhang** [make-all/tuya-local#34]
Below is the list for DPSID&coresponding functions:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/johnnybyzhang/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/johnnybyzhang/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

DPSID | Function | Possibliliies
-- | -- | --
1 | power | Bool
2 | mode | forestwindhigh/low,sleepwindhigh/low
4 | rotation | off,30,60,90,360+,360-
6|Timer|0,1,2,3,4,5,6,7
9 | light | Bool
16 | child lock | Bool
17 | sound | Bool
102 | level | 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

</body>

</html>
plus: the device id is 6c26bcd21d7aa27babaahd

**Comment by make-all** [comment]
Thanks for the info.

Device ID is specific to your device, but if you have a record of the product id (reported as productKey in some places, product_id in others), it might be useful for a future enhancement, since that is common to all Lexy F501 fans, and may be used in future to improve device detection reliability.

The mode possibilities are not totally clear to me.  Is is "forestwindhigh", "forestwindlow", "sleepwindhigh", "sleepwindlow"?  I'm not sure about the sleepwindhigh - normally a sleep mode would use low speeds only to keep the fan quiet, so is it "sleep", "windhigh", "windlow" instead?

**Comment by Johnnybyzhang** [comment]
> "sleepwindhigh", "sleepwindlow"

I have checked and confirmed that there are two sleep modes. One of which operates even slower than another one.

P.S: how do I get the Product ID?

**Comment by make-all** [comment]
Product ID may be printed when your device is discovered, depending on the method that you used to obtain your local key.
Currently the integration does not support discovery, so it is not obtained by the integration.  If you have a PC with python installed, you can get it by:

pip install tinytuya
python -m tinytuya

This will list all the discovered devices on your network.

**Comment by Johnnybyzhang** [comment]
Just checked and confirmed that the Product ID is unqopjvzu4ut6hb0.

**Comment by make-all** [comment]
Thanks the device support has been released in 0.9.0.
