### ISSUE TITLE
States are disordered or missed while open/close operations

### ISSUE THREAD

**Issue by x5500** [make-all/tuya-local#373]
For cover(curtain):

I've noticed that tuya-local reports action complete state at start of movement, if initiated by tyua-local. And misses movement stage if movement was initiated from outside.

```
EXTERNAL OPENS:						TUYA_LOCAL REPORTS:
 ^ Open			23:16:50			^ 		(absent)	(actual opened)
 | Opening		23:16:44			 | 		(absent)
 | Open			23:16:44			 | Open		23:16:44
 | Closed		--------	     		 | Closed	--------	(initial state)
 

IF TUYA_LOCAL OPENS by COMMAND:				EXTERNAL REPORTS:
^			(absent)			Open		23:18:33 	(actual opened)
 | Open			23:18:26			Opening		23:18:26
 | Opening		23:18:26			Open		23:18:26
 | Closed		23:18:15			Closed		23:18:21	(initial state)
 

IF TUYA_LOCAL OPENS by SET POSITION:			EXTERNAL REPORTS:
 ^			(absent)			^ Open		23:43:54 	(actual opened)
  |			(absent)			| Opening	23:43:47
  | Open by cover.set_cover_position	23:43:47	| Open		23:43:47
  | Close				23:41:19	| Closed	23:41:25 	(initial state)

 
 IF EXTERNAL CLOSES:					 TUYA_LOCAL REPORTS:
 ^ Closed			23:31:36		 ^				(actual closed)
 | Closing			23:31:30		 |
 | Closed			23:31:30		 | Closed	23:31:30
 | Open							 | Open		23:27:06	(initial state)
 
 IF TUYA_LOCAL CLOSES by COMMAND:			EXTERNAL REPORTS:
 ^							^ Closed	23:21:52	(actual closed)
 | Closed			23:21:46		| Closing	23:21:46
 | Closing			23:21:46		| Closed	23:21:46
 | Open				23:20:41		| Open		23:20:47	(initial state)


-----------------------------------------
IF TUYA_LOCAL CLOSES BY SET POSITION:			EXTERNAL REPORTS:
^				(absent)		^ Closed	23:41:25	(actual closed)
 |				(absent)		| Closing	23:41:19
 | Closed by cover.set_cover_position	23:41:19	| Closed	23:41:19
 | Open					23:40:58	| Open	23:41:04		(initial state)
```
 
[open_close_experiment_export.txt](https://github.com/make-all/tuya-local/files/10573734/open_close_experiment_export.txt)
[open_close_experiment_debug_log.txt](https://github.com/make-all/tuya-local/files/10573736/open_close_experiment_debug_log.txt)

**Comment by make-all** [comment]
If this is for the Loonas curtain that was added yesterday, the curtain does not actually provide "opening" or "closing" state, so it has to be generated from last command and current position, so can be wrong in some cases.  I am not sure about HA's logic for updating attributes, but it seems that maybe it is only bothering to update the current action when it thinks the curtain should be doing something because it sent a command.

Based on the above table, the Tuya Local reports seem to be more reasonable than the External reports, which always seem to report the target state before reporting any movement.

**Comment by make-all** [comment]
I'm closing this, as I don't see any bug here.  "closing" and "opening" states can only be accurate if the device provides them.  In the case of the open/close by set_position, the last command is "stop", so even if the current_position is moving between 0 and 100, we are unable to tell from a single snapshot whether it is opening or closing, and we do not keep history, nor do I wish to start keeping history just to workaround poorly implemented devices.  As long as open and closed are correctly reported, I don't see this as a major issue.

**Comment by x5500** [comment]
The "external" is a LocalTuya with little patch to invert percent position. 
Both solutions (TUYA-LOCAL and LocalTuya) are inherited from cover component of HA.

Yes, you're right LocalTuya is having it's own problems and too optimistic to report Completed state at the begin of the movements, but it's correct it's state in next state update and informs final state just in time movement completed.

The TUYA_LOCAL component reports final state at the begin of  a movement but not in time movement completed.

**Comment by make-all** [comment]
The wrong information is coming from the device.  Getting rid of the noise from the log, I can see that immediately after sending a command, the device reports dp 2 and 3 as jumping straight to the target position (100 or 0).  Then when the operation completes, the command is changed to "stop" and dp 2 and 3 changed to the actual position of the curtain (which is often 1 or 99 rather than 0 or 100).  There is no intermediate positions coming back from the curtain.  Localtuya is obviously using different logic to determine opening/closing, but it too is having problems with the state that the curtain is reporting.

**Comment by x5500** [comment]
The "original" HA code, for example in mqtt 'cover' have another state logic, little differ from both components.
I think that the problem, that component sometimes confuses 'CLOSE' as command and 'CLOSE' as movement state.

**Comment by make-all** [comment]
I guess that localtuya is also taking the jump in position as a sign that the curtain has finished opening or closing, but it is then changing to opening or closing, probably based on the command changing from stop.

But I am not sure that other curtains have the same behaviour, some don't report position at all, and the current logic needs to handle those as well, which I think only report stop when the curtain was manually stopped in the middle.

**Comment by x5500** [comment]
> I guess that localtuya is also taking the jump in position as a sign that the curtain has finished opening or closing, but it is then changing to opening or closing, probably based on the command changing from stop.

Yes, it is. 

Now as a result in HA:
localtuya device correct report (and draws in intertface, as result) movement state: at the beginning of a movement state and icon is changed to 'Opening' (for example) and at the end - the state (and icon) is changed to the 'Open' or 'Opened' state.
Same behavior i'm try to get from TUYA_LOCAL.


The problem i try to resolve - is link (synchronize) two curtains (motor itself and curtain switch-controller). Make one follow another simultaneously. This link correct works in TUYA itself: On OPEN1 -> OPEN2: On CLOSE1 -> CLOSE2, On STOP1 -> STOP2. Now i try to migrate to HA and local usage of a devices.

**Comment by x5500** [comment]
Here video how it looks in HA interface:
[](url)

https://user-images.githubusercontent.com/90279550/216578056-37876a31-e158-4df4-823c-99b60cc30e03.mp4

**Comment by x5500** [comment]
position state video:

https://user-images.githubusercontent.com/90279550/216580329-3f27eac8-09a9-48d1-8b07-c0d16f74f74c.mp4

**Comment by make-all** [comment]
It seems you have configured multiple integrations to connect to the same device.  It is known that tuya devices do not handle multiple local connections well, what happens if you disable/remove the localtuya connection?  It seems that localtuya is getting all the intermediate position reports, perhaps due to order the integrations were initialised, as based on the logs, we are only ever getting 0, 100, 1 and 99 reported (the latter two only after the "stop" is received).

**Comment by x5500** [comment]
Ok, not a problem to make these tests too. I created this configuration just to compare behavior.

**Comment by x5500** [comment]
Here it is (other than LOCAL_TUYA whole integrations are disabled)

https://user-images.githubusercontent.com/90279550/216582534-f2bc7bc1-e94c-483a-8928-ff2bc95bacc5.mp4

**Comment by x5500** [comment]
As you can see (it's after HA reboot), tuya_local doesn't inform CLOSING state and doesn't report state when movement ends.

https://user-images.githubusercontent.com/90279550/216586747-3b415fa6-f279-43b8-b90a-883620ce9ea8.mp4

**Comment by make-all** [comment]
If you want to change the names of the states, you need to submit an architectural change request to HA project, as that would affect a lot of integrations.

**Comment by x5500** [comment]
> If you want to change the names of the states, you need to submit an architectural change request to HA project, as that would affect a lot of integrations.

 Fully agree with you

Now i try to resolve that tuya_local informs final state earlier than movement was completed. and no report at the time its actually completed. As it was in first message:

IF TUYA_LOCAL OPENS by COMMAND:				EXTERNAL REPORTS:
```
^(absent)			Open		23:18:33 	(actual opened)
 | Open			23:18:26			Opening		23:18:26
 | Opening		23:18:26			Open		23:18:26
 | Closed		23:18:15			Closed		23:18:21	(initial state)
```
