### ISSUE TITLE
Edit Function

### ISSUE THREAD

**Issue by epajfl-00** [make-all/tuya-local#387]
This not a bug, but an enhancement or suggestion and a question.

The ability to edit or change the selected Device yaml file after selection, since once a device type is selected that is it, can't be changed, only delete and start again.
Also, how do choose a device type file other than what comes up on the UI?
In my case I wanted to add an Arlec Smart plug, so I had a look at the available device files and found that Smartplugv2_energyv2.yaml was the best fit, so when I went to config it I was surprised that the various other device files where not listed, basically Smartplugv2.yaml was really the only choice provided. so the obvious question is how to access the other device type options?

**Comment by make-all** [comment]
If they are not offered, then the other device configs are not compatible with your device.  Smartplugv2_energyv2 has a number of extra settings that the smartplugv2 does not have, if your plug does not offer all those extra settings, then it will have problems, including going offline for a few minutes after it crashes due to unexpected input, which has been observed on many Tuya devices before.

Regarding switching the config after initial selection, different configs contain different entities, which are registered in HA when the device is first set up.  If you switch to a different config without removing the device, then those entities will stick around as zombies and will need to be deleted manually.
