### ISSUE TITLE
Request support for [Atomi Smart WiFi Ceramic Heater]

### ISSUE THREAD

**Issue by DrFate09** [make-all/tuya-local#428]
# Log Message

Device matches andersson_gsh_heater with quality of 50%. DPS: {'updated_at': 1676571301.878929, '1': False, '2': 72, '3': 67, '4': 'high', '8': True, '10': True, '11': '0h', '12': 0, '102': False, '103': False}

# Information about DPS mappings

{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":60,\"max\":86,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"auto\"]}"
      },
      {
        "code": "shake",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":60,\"max\":86,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":122,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"auto\"]}"
      },
      {
        "code": "shake",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_left",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"h\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676570788037,
  "tid": "a20c620eae2411eda7608a6d7357cdbb"
}

# Product ID

{
  "result": {
    "active_time": 1645337872,
    "category": "qn",
    "category_name": "Heater",
    "create_time": 1643316630,
    "gateway_id": "",
    "icon": "smart/icon/ay1531317374343k75lf/909a050cae8a9ba450b840011a57aa6f.png",
    "id": "ebcd9c6afb95a6c45ehkqn",
    "ip": "99.6.161.40",
    "lat": "39.6466",
    "local_key": "REDACTED",
    "lon": "-86.1028",
    "model": "AT1632",
    "name": "Heater ",
    "online": true,
    "owner_id": "64496022",
    "product_id": "ojvja3vyqchxrfhk",
    "product_name": "Heater ",
    "sub": false,
    "time_zone": "-05:00",
    "update_time": 1675880867,
    "uuid": "f25b678eeb2dc9f6"
  },
  "success": true,
  "t": 1676571124962,
  "tid": "6ad585e7ae2511eda7608a6d7357cdbb"
}

# Information about how the device functions

![image](https://user-images.githubusercontent.com/22684695/219472225-26bde8b3-23b5-49ea-99fb-698be36cfd9e.png)

Heating modes & safety features
The heater comes equipped with three heat settings: low, high, and ECO mode. Plus, wide-angle oscillation evenly circulates heat throughout the room and shuts off once the air is no longer blowing. For added safety, a tip-over switch instantly turns the heater off if toppled over and sends a phone notification.

Manual: https://manuals.plus/wp-content/uploads/2022/03/Atomi-Smart-Heater-AT1632-User-Guide.pdf
Product page: https://atomismart.com/product/smart-wifi-tower-heater/

**Comment by make-all** [comment]
It might be interesting to get the names for dp 102 and 103 from the iot.tuya.com device debugger (it is inside the project you created, and should show up if you have paired your device using the smartlife app.  You may need to associate your app account with your developer account first).

One of these will be the tip sensor (unless shake" meant that instead of swing_mode) which is mentioned in the manual.

**Comment by DrFate09** [comment]
Is this the information you are looking for? 

![image](https://user-images.githubusercontent.com/22684695/219728609-ac31e4b0-c170-4e12-95e4-eba68cc879f0.png)

**Comment by make-all** [comment]
No sorry, I misspoke. It is on the Device Logs tab that you can access the unlisted do names in a drop-down top left. And in the browser developer tools window if you find the "list" network call after selecting the dp you can find the "code" associated with it in the request parameters.

**Comment by DrFate09** [comment]
- DPID: 1     Description: Power
- DPID: 2     Description: Set Temperature
- DPID: 3     Description: Current Temp.
- DPID: 4     Description: Mode
- DPID: 102     Description: Overtime Notice Switch
- DPID: 103     Description: 设备倾倒或断电 (Google Translate from Chinese to English, "Equipment dumped or powered off")
- DPID: 8     Description: Swing
- DPID 104     Description: Temperature Scale

**Comment by DrFate09** [comment]
@make-all I went ahead and added your YAML file to my local HA to test out your work! It's working great other than one missing setting from the interface, the ability to toggle the heater to swing (DPID 8). I see that you have it included in the YAML but it isn't showing up as an option in the front-end. Do you know why it might not be showing up as a configurable option?

![image](https://user-images.githubusercontent.com/22684695/219833940-8fe39d3e-2720-4601-860f-5b3765ce549f.png)

![image](https://user-images.githubusercontent.com/22684695/219834003-05d55e1a-edaf-4267-8cde-33c35714951e.png)

![image](https://user-images.githubusercontent.com/22684695/219834098-49c43084-9e07-458c-bee6-5847701d4a88.png)

**Comment by make-all** [comment]
Sorry, I missed the _mode off the dp name, so HA is not picking it up as a swing control

**Comment by make-all** [comment]
Support added in 2023.2.3

**Comment by neozizen** [comment]
> @make-all I went ahead and added your YAML file to my local HA to test out your work! It's working great other than one missing setting from the interface, the ability to toggle the heater to swing (DPID 8). I see that you have it included in the YAML but it isn't showing up as an option in the front-end. Do you know why it might not be showing up as a configurable option?
> 
> ![image](https://user-images.githubusercontent.com/22684695/219833940-8fe39d3e-2720-4601-860f-5b3765ce549f.png)
> 
> ![image](https://user-images.githubusercontent.com/22684695/219834003-05d55e1a-edaf-4267-8cde-33c35714951e.png)
> 
> ![image](https://user-images.githubusercontent.com/22684695/219834098-49c43084-9e07-458c-bee6-5847701d4a88.png)

@DrFate09 would you please share how you took his yaml file and used it in your local HA?  I have the exact same issue as you.

**Comment by DrFate09** [comment]
@neozizen 

What version of HA are you using? Your controls for the heater look different from mine. I am on the latest release.

Also, you should not need to manually add the YAML to your HA. If you install the Tuya Local integration with HACS, you can then add the heater using the "Add Integration" under Devices & services. I did not have to do any special configuration to make the swing mode appear. 

![image](https://github.com/make-all/tuya-local/assets/22684695/3c2d1919-1687-448c-a877-4476905ffb83)

**Comment by neozizen** [comment]
@DrFate09 ty for the response!

When I add the integration, the integration appears to go the same as you outlined above.  I did name the integration the same as you have named instead of the andersson_gsh_heater name.

For some reason my temperature readings are all out of line.

![Snag_95906de](https://github.com/make-all/tuya-local/assets/10244869/f55c8d73-f590-4c9b-a60f-1d8d99112747)
![Snag_9593149](https://github.com/make-all/tuya-local/assets/10244869/1bf21589-13ab-4494-8dc0-2cbc0b251404)
![Snag_9595cce](https://github.com/make-all/tuya-local/assets/10244869/ff2e106f-2f73-4f25-9e06-9f9614c4cf75)
![Snag_9596af7](https://github.com/make-all/tuya-local/assets/10244869/b74bf56f-9bb5-4e8e-a393-8491f4dd9fec)
![Snag_95975c4](https://github.com/make-all/tuya-local/assets/10244869/40e8373f-442e-4f8c-831e-616d013ed2fd)
![Snag_95980f0](https://github.com/make-all/tuya-local/assets/10244869/6f51de2a-d1d3-4ae9-9693-ae7a010beac1)
![Snag_9598891](https://github.com/make-all/tuya-local/assets/10244869/7b61e93f-693c-4205-90d7-85df2287388f)

**Comment by make-all** [comment]
Rather than renaming the heater after it is added, you need to select the correct config at the second screeenshot above (atomi, not anderson).

**Comment by DrFate09** [comment]
@make-all I do have a question for you now that this issue is active again.

I have noticed in comparison to my Google Nest thermostat, the Atomi Smart Heater does not show the "Heating" live text using the same Thermostat card. Do you know if any information might be missing from the YAML that would enable that also for the Atomi? 

![image](https://github.com/make-all/tuya-local/assets/22684695/514367b6-4410-476e-9ee4-0c8f60122eed)

**Comment by neozizen** [comment]
Hello @make-all ty for the response and your comments helped me.  I screwed up.

So i deleted the integration and started over.
![Snag_969d82a](https://github.com/make-all/tuya-local/assets/10244869/974c5d97-6a5a-43e5-bce4-6605ed0c370d)

On the second stage my heater did not show up.  I thought this was normal because @DrFate09 reported this up above so I just renamed it.  However your comments made me think this should not be correct.  I was also looking at your Stage Two directions and kind of thought it was okay if it was not a direct match.  Anyway, I assumed it needed to be an exact match so I went back and double checked my model number.
![Snag_96a8293](https://github.com/make-all/tuya-local/assets/10244869/182cbf80-fe89-4440-bd0b-1b44da97f804)
![Snag_96a8c28](https://github.com/make-all/tuya-local/assets/10244869/1090c712-6433-4edf-baf5-6cf93c531440)

Sure enough by model is AT1635.
![Snag_96cb2f0](https://github.com/make-all/tuya-local/assets/10244869/f47c6044-0dba-48d0-8be6-74c4e1578816)

Not the model AT1632.
![Snag_96cef9b](https://github.com/make-all/tuya-local/assets/10244869/ef7445ac-b6be-4b0d-a1ab-1541160a870e)

This is the issue, isn't it?  I need to submit a request to have my device added, correct?

Best,
Jeff

**Comment by make-all** [comment]
Yes, the issue seems to be that the AT1635 is not compatible with the AT1632 (but still a close match to the Andersson, so probably just a minor difference like missing a sensor or config option).  If you submit a new device request with the log and any additional information you can collect, then it should be obvious what the differences are.
