### ISSUE TITLE
Supervison hang when tuya is updated to any version over 2023.2.0

### ISSUE THREAD

**Issue by blamaz** [make-all/tuya-local#455]
**Describe the bug**
Supervisor hang at reboot when updated to any version over 2023.2.0 and unable to setup platform tuya_local.

**To Reproduce**
Update to a version over 2023.2.0.

**Expected behavior**
Expected to work the same with any versions.

**Additional context**
Everything work as expected before upgrading.
Tried uninstalling and reinstalling whitout success.
Will stay on  2023.2.0 for now.

If the bug involves a device, then please include device diagnostics from
Bug not coming from device.

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 10:26:58 AM (1 occurrences)
Last logged: 10:26:58 AM

Unable to prepare setup for platform tuya_local.switch: Platform not found (No module named 'custom_components.tuya_local.switch').

Logger: homeassistant.util.async_
Source: util/async_.py:182
First occurred: 11:27:44 AM (1 occurrences)
Last logged: 11:27:44 AM

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 70: self._api = tinytuya.Device(dev_id, address, local_key)

Core log
Failed to refresh device state for Catit Pixi Smart Fountain.
10:29:59 AM – (ERROR) tuya_local (custom integration) - message first occurred at 10:28:18 AM and shows up 3 times
Catit Pixi Smart Fountain receive loop terminated by exception Sensor sensor.catit_pixi_smart_fountain_water_level is providing enum options, but is missing the enum device class
10:29:59 AM – (ERROR) tuya_local (custom integration) - message first occurred at 10:28:41 AM and shows up 3 times
Failed to refresh device state for Catit Pixi Smart Fountain
10:29:46 AM – (ERROR) tuya_local (custom integration)
Unable to prepare setup for platform tuya_local.switch: Platform not found (No module named 'custom_components.tuya_local.switch').
10:29:43 AM – (ERROR) setup.py - message first occurred at 10:26:58 AM and shows up 4 times
Platform tuya_local does not generate unique IDs. ID 23017707bcff4d4f853a-filter_replaced already exists - ignoring button.catit_pixi_smart_fountain_filter_replaced
10:29:43 AM – (ERROR) button - message first occurred at 10:29:43 AM and shows up 2 times
Error unloading entry Catit Pixi Smart Fountain for button
10:29:43 AM – (ERROR) tuya_local (custom integration)

**Comment by make-all** [comment]
You seem to have corrupted your install somehow so files are missing.  How are you installing this integration?

**Comment by make-all** [comment]
There seem to be a mix of real issues introduced by recent changes and strange issues due to your installation.
```
Unable to prepare setup for platform tuya_local.switch: Platform not found (No module named 'custom_components.tuya_local.switch').
```
This is a problem with your install I think.  I have smartplugs working here, so the tuya_local.switch platform is definitely not completely broken.

```
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 70: self._api = tinytuya.Device(dev_id, address, local_key)
```
This happens if your IP address is not set, and is explained in bug #407 

```
10:29:59 AM – (ERROR) tuya_local (custom integration) - message first occurred at 10:28:18 AM and shows up 3 times
Catit Pixi Smart Fountain receive loop terminated by exception Sensor sensor.catit_pixi_smart_fountain_water_level is providing enum options, but is missing the enum device class
```

This is due to the recent support added for the "enum" sensor device class.  I did not expect that Home Assistant would be this strict about requiring the device class to be set if options are provided.  In this case, the Water level sensor should actually be an enum type sensor, so I have set it in the config.  But there are also other devices where options are available as a side effect of them mapping values into a percentage range, so I also have to avoid this error for those by limiting sensor.options to only return actual enum values.

```
10:29:43 AM – (ERROR) setup.py - message first occurred at 10:26:58 AM and shows up 4 times
Platform tuya_local does not generate unique IDs. ID 23017707bcff4d4f853a-filter_replaced already exists - ignoring button.catit_pixi_smart_fountain_filter_replaced
```
It seems that HomeAssistant has stopped treating two different entity types with the same id as separate, and is now requiring strictly no duplicate ids.  I will have to look into whether it is possible to migrate existing entity ids so as not to lose any user customizations or have new entities defined when I change the ids to include the entity type to avoid these errors.

**Comment by blamaz** [comment]
I've installed from hacs. I've tried to delete component from integration than from hacs and verified that the folder was gone in custom_components, reboot and reinstall but problem remain. Don't know where to look maybe in .storage.

**Comment by make-all** [comment]
Can you try Redownload from the menu in HACS, and choose "main" as the version.

It is possible that the first error is caused by the second, which I have already fixed.

**Comment by blamaz** [comment]
Thank you for your help, much appreciated. I will try when i get back home saturday.

**Comment by make-all** [comment]
Thanks, I have added the two dps for the 2023.2.4 release.
