### ISSUE TITLE
Smart plug shows only switch entity

### ISSUE THREAD

**Issue by voed** [make-all/tuya-local#72]
Hi. I have added my smart plug as "smartplugv2" device, but there's just switch entity without energy monitoring.
Log info:
```Device matches smartplugv2 with quality of 31%. DPS: {'1': True, '9': 0, '17': 100, '18': 2368, '19': 4866, '20': 2148, '21': 1, '22': 628, '23': 30636, '24': 17426, '25': 2400, '26': 0, '38': 'memory', '41': '', '42': '', '46': False, 'updated_at': 1636718247.1290212}```
Debug info:
![image](https://user-images.githubusercontent.com/10352360/141464942-27611dac-47c1-4b48-8314-81cdb1044312.png)
![image](https://user-images.githubusercontent.com/10352360/141464981-2862370e-4f9e-433f-b846-78ca19894ff1.png)

**Comment by make-all** [comment]
It looks like it has been detected as smartplugv2, which means you have voltage, current and power attributes available.

**Comment by voed** [comment]
According to my measurements:
20 is voltage
19 is power
18 is current
38 is relay status `memory`/`on`/`off`
46 is switch overcharge 0/1 (no idea what it is, but there's a setting in smart life app)
Can do some further inspections if needed.

**Comment by make-all** [comment]
I guess the most useful additional one is the energy measurement, which would remove the need to configure an additional integration sensor based on the power.

38 I can add as a select for the Power on state.  The rest can stay as unknown attibutes (overcharge I can name, but without knowing what it is and range of valid values, it isn't really useful as a separate entity).

What is the brand and model of this switch?  Or since it seems to just extend smartplugv2, maybe it can just be given a generic name like advanced_smartplugv2.

**Comment by voed** [comment]
The brand is "CBE", but i'm pretty sure its OEM device so yes, better to make some generic name. Maybe smartplugv2_ex (as "extended")?
I'll try to get energy measurement somehow, but for now all other attributes looks static.

**Comment by make-all** [comment]
It seems to be based on Tuya's "Smart Metering Socket" solution, so I'll use that for the generic name.
https://solution.tuya.com/projects/CMa8u91n663sbf

The overcharge feature is to turn the switch off when the current drops (to indicate a battery has finished charging). Since it is numeric rather than true/false, it may be setting a threshold below which to turn off.  If the smartlife app just has a switch for this, I think we can assume that 0 disables the feature and 1 enables it, with no other possible values.

**Comment by make-all** [comment]
There seems to be dps level documentation here:
https://developer.tuya.com/en/docs/iot/product-standard-function-introduction?id=K9tp15ceh63gr
So I think I can make a fairly complete implementation from that.

**Comment by voed** [comment]
Oh, sorry, overcharge is boolean, not numberic.

**Comment by voed** [comment]
Also found some discussion about energy monitoring: https://github.com/codetheweb/tuyapi/issues/121#issuecomment-478657011
A theory that power consumption data sent from smartphone via Smart Life app seems fair to me. It explains why android sometimes reporting about increased battery usage from this app.

**Comment by voed** [comment]
Well, i was polling my socket every 2 seconds for 6 hours, there's no any changes in attributes except 18, 19, 20.
Also i removed smart life app from my phone, but "Add electricity" still exists in tuya log:
![image](https://user-images.githubusercontent.com/10352360/141654329-294df3d7-2675-4e05-8545-70b694159a97.png)
Looks like it just calculated on server side or something.

Here's polling result:
[tuya_log.txt](https://github.com/make-all/tuya-local/files/7532507/tuya_log.txt)

**Comment by make-all** [comment]
0.10kWh is consistent with dps 17, which is what the docs in my last comment said.  So I will export that as an energy sensor.  If it is not accurate, then you will have to create an integration sensor in HA based on the power sensor (but if the device plugged into the socket is a switched mode power supply or other device that has non-constant power usage, it may be more accurate, as the power could be reporting peaks).

**Comment by voed** [comment]
Ok. Thanks.

**Comment by make-all** [comment]
Still, 3.5 hours at a little over 500W should have seen that reading go up to 1800 at least, not stay on 100.  There may be some other action needed to get it to update its energy usage reporting, or the feature is actually missing and hardcoded to report 100.

**Comment by make-all** [comment]
Looking at the server logs, it might be sending out 100 every time it has used another 0.1kWh, and expects the server to catch them all and add them.  That isn't very useful, the chances of missing one is too high, so I think it may be better to go with an integration of the power sensor in HA instead.

**Comment by voed** [comment]
![image](https://user-images.githubusercontent.com/10352360/141686331-91aadb72-ff26-4958-a9e8-c144343cd341.png)
Works fine. Thanks again.
