### ISSUE TITLE
Request support for COSTWAY Portable Air Conditioner

### ISSUE THREAD

**Issue by Yersi88** [make-all/tuya-local#782]
# Log Message

```
Device matches mellerware_citymove_vacuum with quality of 33%. DPS: {"updated_at": 1686439455.6183114, "1": true, "2": 20, "3": 21, "4": "cold", "5": "low", "20": 0, "103": false, "107": 68, "109": 0}
```

# Information about DPS mappings
        "1 (value: True)",  -> Power ON/OFF
        "2 (value: 22)", -> Target Temperature 
        "3 (value: 23)", -> Room Temperature
        "4 (value: cold)", -> Mode, Can be: cold, fan, dehumidifier
        "5 (value: low)", -> Fan Speed: low, high

BELOW HERE I'M NOT SURE, alto these are not so important.
        "20 (value: 0)", 
        "103 (value: False)", -> This one might be indicator that the water tank is full.
        "107 (value: 72)",
        "109 (value: 0)"

```
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1686442738646,
  "tid": "8f31603407ed11eea795ce4cada2c678"
}


```

# Product ID
86sjxqebxymrjt3z

# Information about how the device functions

This is a portable AC unit. You just select temperature, mode, fan speed on the device display or in the tuya app.

**Comment by make-all** [comment]
Tank full indicators are often rolled into a general fault code, so could be 20 or 109 too.  I think I will leave them all "unknown" so you can monitor over time and figure out which is indicating the tank full rather than making an assumption based on nothing.  72F is 22C, so 107 could be a Fahrenheit target temperature, in which case 103 could be the C/F switch.

The other missing info is the range for target temperature.

**Comment by make-all** [comment]
Awaiting feedback on the range for temperature setting.

**Comment by Yersi88** [comment]
Hi, sorry for long wait. I created pull request with my current config #814 

Included correct modes and temperature ranges.
