### ISSUE TITLE
Position unknown wistar_roller_blind_nopos after update from 2023.4.2 to 2023.5.2

### ISSUE THREAD

**Issue by mihsu81** [make-all/tuya-local#794]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Roller blinds wistar_roller_blind_nopos report unknown position and incorrectly reversed after the upgrade from 2023.4.2 to 2023.5.2.

**To Reproduce**
Upgrade from 2023.4.2 to 2023.5.2.

**Expected behavior**
Position should be properly reported, as well as the reversed status.

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[config_entry-tuya_local-3ec41129760708c24e7b4bc61de24ce6.json.txt](https://github.com/make-all/tuya-local/files/11734557/config_entry-tuya_local-3ec41129760708c24e7b4bc61de24ce6.json.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
No messages

Before the upgrade 
![image](https://github.com/make-all/tuya-local/assets/40715497/63f7bf48-87d3-4b37-927b-16a4824ee530)
After the upgrade
![image](https://github.com/make-all/tuya-local/assets/40715497/d3869414-2c2d-4d7e-8278-c5920903eb5b)
![image](https://github.com/make-all/tuya-local/assets/40715497/8120ca28-dcef-4172-a461-91b3df8c73b7)

**Comment by make-all** [comment]
Unknown is correct for this device, as the current_position dp was removed from the config due to unreliability.
Reversed is just reporting the position of the switch as reported by Tuya.  It used to reverse the positions as well, but that is incorrect, it is just a switch to change the device behaviour.  If positions are incorrect, then this is a rare device where the Tuya position agrees with HA's position of 0 = closed, 100 = open

**Comment by mihsu81** [comment]
In 2023.4.2 and previous versions it would report the status based on _dp_id 102 percent_control_ regardless of the broken _dp_id 112 currenPosition_.
Screenshot from 2023.4.2
![image](https://github.com/make-all/tuya-local/assets/40715497/75f189fa-64a6-4633-80c2-3a2786f802ff)

Regarding the Reversed switch, I've adjusted the device yaml with https://github.com/make-all/tuya-local/pull/801 and now it matches Tuya and the state pre-2023.5.0.
P.S. I've corrected the versions from 2022 to 2023. 😁

**Comment by tavicu** [comment]
The problem comes because the `is_closed` function return None every time for devices that don't have current_position attribute. I think this is wrong.

I have forked the repo and this is the only change I made in order to work everything as it should: https://github.com/tavicu/tuya-local/commit/0770a7cdbf598bc43e00ec1573373bf73c8faf1c#diff-23349e6c1929c5523cf5bec8d7c397836792651cfc2130a3c9b5b8341ba34380

**Comment by make-all** [comment]
Returning None from is_closed when the state cannot be determined is correct according to the documentation for the cover entity.  Returning a value leaves one of the open or closed controls disabled in the UI, so it is necessary to be certain the device is either fully open or fully closed.

Unfortunately, not only your device needs to be supported, other devices do too, and there is too much variation in the behaviour of Tuya devices to be certain about anything in the absence of a working current_position dp.

The fact that this device has a current_position dp, but it does not work properly points to this device being one of the more problematic ones, so catering to this device at the expense of others would be the wrong approach.

**Comment by tavicu** [comment]
Why not making a fallback and check position?

From documentation: "If the cover is closed or not. if the state is unknown, return None. Used to determine state."

Why you say you can't determine the correct state? Because you can. Position == 0 ? then it's closed. It's not like you don't have the position at all to return None. You know if it's closed or not in order to return a correct value.

**Comment by make-all** [comment]
Because the position is wrong _(write only, and not updated according to actual position) on many devices.  So falling back to it gives incorrect results, including leaving the curtain in the open or closed position when the position is reported as the opposite.

**Comment by tavicu** [comment]
So because of some devices that don't report the correct value, you choose to break the ones that works ok?

If you know that kind of devices, then add an attribute for the config to report None all the time, but don't break all of the devices, it's not right! Especially when they are reporting correctly.

**Comment by make-all** [comment]
This device is one of the devices that reports an incorrect value! It was explicitly requested to ignore the currrent_position because it does not seem to update as expected.

**Comment by tavicu** [comment]
Ok, but what about other cover devices? Because the changes made with 2023.05 affect all of them.

I for example have multiple devices from zemismart which reports only the position, correctly. They don't have a `current_position` attribute. And because of the changes they all report as Unknown when this is not true ... :)

**Comment by tavicu** [comment]
If you ask me the function should look like this
```
def is_closed(self):
    """Return if the cover is closed or not, if it can be determined."""
    state = self._current_state
    if state is None:
        # If we return false, and is_closing and is_opening are also false,
        # HA assumes open.  If we don't know, return None.
        return self.current_cover_position == 0
    else:
        return state == "closed"
```

**Comment by make-all** [comment]
The current_pos is already taken into account in the _current_state property.

**Comment by tavicu** [comment]
Yes, but not the position :)

Having a device that reports only `position` will result in `is_closed` always being `None`

**Comment by mihsu81** [comment]
With https://github.com/make-all/tuya-local/commit/8c918f6a82c7b9f66d123dbd86263113c8994148 the shutters appear either fully open or fully closed which is good but not Open xx% like in 2023.4.2.
There's also another issue introduced by https://github.com/make-all/tuya-local/commit/8c918f6a82c7b9f66d123dbd86263113c8994148. The shutters respond to the first service call cover.toggle and stop responding until they're either fully closed or fully open.
From 2023.5.0 the shutters wouldn't stop while moving when I issue a service call cover.toggle, and they'd start the opposite action either open or close.
In 2023.4.2 the shutters would stop while moving when I issue a service call cover.toggle.

**Comment by make-all** [comment]
When the indication was "Open xx%", were both open and close controls available?

Another user reported that the Open button was disabled when the device was stopped in a partially open state.

**Comment by mihsu81** [comment]
Both open and close controls were available.

![image](https://github.com/make-all/tuya-local/assets/40715497/03a5b381-202e-4d65-95c6-700a971a302d)

**Comment by mihsu81** [comment]
But the issue is not solved.
