### ISSUE TITLE
ChangeRequest support for weau_pool_heatpump_v2.yaml

### ISSUE THREAD

**Issue by frankie-boy-hgv** [make-all/tuya-local#808]
Hi,

Not sure how to ask it, but I'll try this way.
Is it possible to make presets in the weau_pool_heatpump_v2.yaml.
I've made some small changes on my setup, but I would like them integrated in the official release.

    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: preset_mode
          conditions:
            - dps_val: sheat
              value: heat
            - dps_val: eheat
              value: heat
            - dps_val: bheat
              value: heat
            - dps_val: scool
              value: cool
            - dps_val: ecool
              value: cool
            - dps_val: bcool
              value: cool
            - dps_val: auto
              value: heat_cool

and the mapping:

    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: sheat
          value: quiet_heat
        - dps_val: bheat
          value: quick_heat
        - dps_val: eheat
          value: smart_heat
        - dps_val: scool
          value: quiet_cool
        - dps_val: bcool
          value: quick_cool
        - dps_val: ecool
          value: smart_cool
        - dps_val: auto
          value: auto

Regards,

Frank

**Comment by frankie-boy-hgv** [comment]
Hi,

I have the mapping Eco / Silent / Quiet for Cool and Heat. And just Auto.
I wasn't sure of the mapping, so I mapped Silent Heat to quiet_heat.
Eco seemed smart to my, so I mapped it to smart_heat.
I might have been wrong :-)

Regards,

Frank

**Comment by frankie-boy-hgv** [comment]
![Screenshot_20230616_180408_Tuya Smart](https://github.com/make-all/tuya-local/assets/70746913/cc43b088-d7ac-424e-9215-b546fe3607b8)

**Comment by frankie-boy-hgv** [comment]
Thnx! Got the code and copied it in my file. Works awesome.
Do you have an idea how to sort the presets in the climate card?
It's a but random now, after each restart 😀

**Comment by make-all** [comment]
No, sorting is something I need to look at, I guess I may need to use something other than the default Python dictionary to pass values back to Home Assistant with, or the problem may be in the front end, which is outside my control.

**Comment by frankie-boy-hgv** [comment]
thnx, not the best solution but
`return sorted(self._preset_mode_dps.values(self._device), reverse=True) in climate.py`
made it a bit better ;-)

**Comment by make-all** [comment]
I found what was causing the order to be lost, and have fixed it.  The list was being de-duplicated by converting to a set and back to a list.  A set has no order,so that was causing the list to lose its order.

**Comment by frankie-boy-hgv** [comment]
Yep, it's fixed:

**Comment by Soepgroenten** [comment]
Hi There,

I just got the Tuya local update and things looked somewhat different due to this request. Things seem to be somewhat more streamlined but there's a down side
Before the presets were called Eco heat and Boost heat. Those names were pretty straight forward and equal to the Tuya standards. Therefore I prefer the old names over the new names.

I guess Quick heat = Boost Heat and Quiet Heat = Eco heat?

In my case the heatpump isn't any more quiet regardless using the Quiet Heat mode so in that case the name doesn't also represents it's function.

I believe there's a difference between models and it's heat/cool functions and especially the naming conventions behind them.

I can live with the new names but this way the integration does not equal to Tuya anymore, just to let you know.
 Personally I think the different models should be categorized in a few sets of configurations with each of them having their natural names for their functions to keep as Close to how the device and it's Tuya integration is designed.

**Comment by make-all** [comment]
What you are calling "Tuya standards" are not standards at all, every device manufacturer chooses their own naming, but there is a pattern for pool heatpumps described above.  In this case, the manufacturer uses Silent, Eco, Boost, others will use Eco, Smart, Performance, or Silent, Smart, Boost, Quiet, Normal, Quick.   The pattern seems to be one mode is running the compressor at low speed constantly, and called Quiet, Silent or Eco, another is running the compressor at full speed constantly, called Boost, Quick or Performance, and another is automatically switching between speeds as needed, called Smart, Normal, Eco or Auto.  It is more important to me to make translation simple than to match the original manufacturer's naming perfectly, so I have chosen to label these as Quiet, Quick and Smart.

**Comment by frankie-boy-hgv** [comment]
Quiet = Silent
Smart = Eco
Quick = Boost
