### ISSUE TITLE
Arlec Smart Plug Lag

### ISSUE THREAD

**Issue by LintHart** [make-all/tuya-local#85]
Hi guys,

I've just bought of the Arlec Smart Sockets with Energy Meter PC191HA and it has integrated with your plug-in beautifully.
I'm really appreaciting the new options to create additional sensors from the power meters etc. 

I was wondering if there is any way to reduce the lag between my soft swtich in Home Assistant and the Relay? Its a good second if not close to feeling like 2
Pulling the same plug in through "LocalTuya", there is no lag but I much rather the setup and more local product support you have going.

(Thank you also for the flawless configuration on the arlec ceiling fan without light. I may look into an additional one with light so I hope to see it in your supported list one day)

Cheers

Linton Hart

**Comment by vampywiz17** [comment]
I go to the site to open a exact same issue :)

I affect the same problem. The localtuya and the official tuya app (via wifi) is no lag, but this integration, i also notice abot 1.5 sec lag... 

would be good to solve this...

**Comment by make-all** [comment]
Now that I've gotten the backlog of new devices out of the way, I'll take a look at rewriting the rate limiting logic so that it does not delay isolated commands.

**Comment by LintHart** [comment]
> 

That's very exciting thank you. I look forward to any progress that can be made.

**Comment by make-all** [comment]
I reduced the delay for sending the first command in a set from 1s to 10ms.  Subsequent commands within 1s of the previous one will still have the 1s delay to reduce problems with the device not being ready to handle the command (I say reduce rather than avoid, because different devices have different downtimes after being sent a command and 1s was a compromise to avoid most problems without delaying too much - 3s or sometimes even 10s is needed to avoid all problems)

Try 0.14.0 and see if it resolves the lag enough to consider this closed.

**Comment by vampywiz17** [comment]
@make-all 

i tested it a different device and this change is reduce the lag!
