### ISSUE TITLE
Slow reaction time

### ISSUE THREAD

**Issue by Anashost** [make-all/tuya-local#876]
Thanks for your work on this integration,
Coming from Local-Tuya I've noticed the devices configured with Tuya Local has slower reaction time while Local-Tuya was almost instant.

I've light bulbs and switches working with 3.3/3.4/3.5 protocols all of them has slowness most of the times, mainly with on/off, brightness actions.

So, is this something you aware of, and can be fixed in future releases?

And I'm wondering if you're planning of implementing local key retrieval feature in future releases.

Have a nice day.

**Comment by make-all** [comment]
Fetching keys from the cloud is covered under #10.

The slowness you are talking about happens because of rate-limiting to ensure stability.  Some devices become unstable if sent commands too close together, so second and subsequent commands are delayed which you might notice if you are toggling rapidly or turning the brightness slowly but steadily.  Unlike localtuya, this integration is not aimed at developers who like to have full control and deal with the issues like this themselves if it affects them, and takes the approach of lowest common denominator.
